import { DotGothic16 } from "next/font/google";
import "./globals.css";

const inter = DotGothic16({ weight: "400", subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header>
          <ul className="flex m-5">
            <li className="mr-6">
              <a className="text-green-600 hover:text-green-800" href="/">
                Home
              </a>
            </li>
            <li className="mr-6">
              <a
                className="text-green-600 hover:text-green-800"
                href="/carrier"
              >
                Carrier
              </a>
            </li>
            {/* <li className="mr-6">
              <a className="text-green-600 hover:text-green-800" href="/job">
                Job
              </a>
            </li> */}
            <li className="mr-6">
              <a className="text-green-600 hover:text-green-800" href="/about">
                About
              </a>
            </li>
          </ul>
        </header>

        {children}
      </body>
    </html>
  );
}
